import hashlib
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Side(str, Enum):
    LONG = "LONG"
    # SHORT is intentionally not implemented yet (see baseline.py) — the enum
    # already carries the second member so nothing downstream needs to change
    # shape when a short strategy is added.
    SHORT = "SHORT"


class ReasonCode(str, Enum):
    TREND_CONFIRMED = "TREND_CONFIRMED"
    MOMENTUM_CONFIRMED = "MOMENTUM_CONFIRMED"
    VOLUME_CONFIRMED = "VOLUME_CONFIRMED"
    # Phase 22: a Signal built by risk.sizing.build_signal_for_buy from a
    # decision_engine BUY label -- did NOT necessarily satisfy
    # TrendMomentumBaseline's own SMA/RSI/MACD/volume rule (a different,
    # independent condition: market_intelligence's composite/trend/momentum
    # sign-agreement). Kept distinct so a Signal's provenance is never
    # misrepresented as "the baseline strategy fired here."
    DECISION_ENGINE_SCORED = "DECISION_ENGINE_SCORED"
    RANDOM_BASELINE = "RANDOM_BASELINE"
    """Strategy science Phase 5 -- a signal generated by the random-entry
    baseline (backtesting/random_baseline.py): entry timing chosen by a
    seeded RNG, with NO trend/momentum/volume condition at all. Kept
    distinct for the same reason DECISION_ENGINE_SCORED is: a Signal's
    provenance must never be misrepresented as "a real strategy fired
    here" when it did not."""
    PULLBACK_CONFIRMED = "PULLBACK_CONFIRMED"
    """STRATEGY EDGE DISCOVERY mission, Phase B -- a signal generated by
    strategy/pullback_continuation.py's PullbackContinuationStrategy: an
    uptrend that recently showed real strength (RSI14), has since cooled
    into a pullback zone, and is resuming upward on the entry bar
    itself. Distinct from TREND_CONFIRMED/MOMENTUM_CONFIRMED (the
    baseline's own immediate-alignment conditions) since this strategy's
    entry TIMING rule is the one thing under test, not the baseline's
    trend/momentum definitions themselves."""
    MEAN_REVERSION_OVERSOLD = "MEAN_REVERSION_OVERSOLD"
    """BUILD THE REAL TRADING BRAIN mission -- a signal generated by
    quant_research/mean_reversion_signal.py's MeanReversionSignalStrategy
    (H_MEANREV_001): a large negative zscore_close_20 (short-term
    oversold), an ENTIRELY DIFFERENT and independent market mechanism
    from every TREND_CONFIRMED/MOMENTUM_CONFIRMED/PULLBACK_CONFIRMED
    signal (all trend-CONTINUATION claims) -- kept distinct for the same
    "provenance must never be misrepresented" reason every other
    strategy-specific code above already is."""
    RELATIVE_STRENGTH_CONFIRMED = "RELATIVE_STRENGTH_CONFIRMED"
    """BUILD THE REAL TRADING BRAIN mission -- a signal generated by
    quant_research/relative_strength_signal.py's
    RelativeStrengthSignalStrategy (H_RELSTRENGTH_001): positive
    relative_strength_20 versus the symbol's own benchmark index, a
    single-symbol approximation of Family D (cross-sectional relative
    strength) -- kept distinct for the same "provenance must never be
    misrepresented" reason every other strategy-specific code above
    already is."""
    BREAKOUT_CONFIRMED = "BREAKOUT_CONFIRMED"
    """BUILD THE REAL TRADING BRAIN mission -- a signal generated by
    quant_research/breakout_signal.py's BreakoutSignalStrategy
    (H_BREAKOUT_001): a Donchian-style breakout above the prior 20-bar
    high, Family C (breakout quality) -- kept distinct for the same
    "provenance must never be misrepresented" reason every other
    strategy-specific code above already is."""
    CROSS_SECTIONAL_LAGGARD = "CROSS_SECTIONAL_LAGGARD"
    """EDGE DISCOVERY mission -- a signal generated by
    quant_research/cross_sectional_strategy.py's
    CrossSectionalLaggardStrategy (H_XSECT_001): the symbol is newly in
    the bottom quintile of the WHOLE UNIVERSE ranked by trailing 60-day
    return on this date (quant_research/cross_sectional.py's
    attach_bucket_membership_column, computed once across all 32
    symbols, not from this symbol's own history alone) -- an ENTIRELY
    DIFFERENT mechanism from RELATIVE_STRENGTH_CONFIRMED (that code
    fires on OUTPERFORMANCE vs. a single benchmark; this one fires on
    UNDERPERFORMANCE vs. the whole peer universe) and from
    MEAN_REVERSION_OVERSOLD (that fires on the symbol's own price
    z-score, with no cross-symbol comparison at all) -- kept distinct
    for the same "provenance must never be misrepresented" reason every
    other strategy-specific code above already is."""


class Signal(BaseModel):
    """A deterministic, machine-readable trade candidate.

    `stop_price`/`target_price` are absolute levels fixed at signal time from
    the generating bar's close and ATR — NOT the eventual fill price. The
    execution simulator fills at the *next* bar's open (see
    backtesting/execution.py), which may already be through one of these
    levels on a gap; that is handled explicitly there, not silently ignored.
    """

    model_config = ConfigDict(frozen=True)

    symbol: str
    generated_at: datetime  # the bar this signal was formed on ("bar N")
    side: Side
    reference_price: float = Field(description="Close of the generating bar. Informational only, not a fill price.")
    stop_price: float
    target_price: float
    risk_reward: float = Field(gt=0)
    strategy_name: str
    reason_codes: list[ReasonCode]
    decision_id: str | None = Field(
        default=None,
        description=(
            "LIVE SYSTEM HARDENING mission, Issue 3 (correlation/traceability) -- the "
            "decision_engine.models.Decision.decision_id this signal was built for, when it came "
            "from that path (risk.sizing.build_signal_for_buy). None for a signal that never went "
            "through decision_engine (e.g. a plain strategy.contracts.Strategy in live/pipeline.py's "
            "LiveSimPipeline, or a backtest) -- honestly absent, never fabricated. Optional/additive: "
            "every pre-existing persisted Signal (paper/store.py's own model_dump_json() rows) "
            "deserializes with decision_id=None automatically, no migration needed. This is the "
            "smallest correlation key that closes a REAL, live-confirmed gap: a real paper "
            "JournalEntry had no stored link back to the Decision/PredictionRecord that produced it "
            "-- decision_id, already present on both Decision and PredictionRecord, now also flows "
            "through Signal -> JournalEntry (paper/models.py), making it the de facto correlation ID "
            "across the whole chain without inventing a second, parallel ID scheme."
        ),
    )

    def stable_id(self) -> str:
        """A deterministic identity for THIS exact signal occurrence — same
        symbol/bar/strategy/side/levels always hashes to the same ID, so
        generating "the same" signal twice (e.g. re-running a strategy over
        the same bar) yields the same ID rather than a fresh random one.
        This is what Phase 6's paper-trading idempotency keys off of (spec
        §8) — no separate ID counter or database sequence needed.
        """
        raw = "|".join(
            [
                self.symbol,
                self.generated_at.isoformat(),
                self.strategy_name,
                self.side.value,
                repr(self.reference_price),
                repr(self.stop_price),
                repr(self.target_price),
            ]
        )
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:24]
