"""Phase 4.5 §21: proves the existing LangGraph/Ollama layer can consume the
deterministic pipeline's output and explain it — without being able to
change it. This is NOT wired into run_backtest or any live trading path; it
is a standalone consumer, matching spec §22's boundary ("Use RAG/LLM for
explanation... never to determine RSI, MACD, entry, stop, PnL, drawdown").

`explain_signal` takes already-computed, already-decided objects and returns
only a SignalExplanation (schemas/explanation.py) — a type with no field
that could hold a revised entry, stop, target, quantity, or PnL. The
deterministic engine remains the sole source of truth for all of those.
"""

from market.context import MarketContext
from risk.contracts import RiskDecision
from schemas.explanation import SignalExplanation
from strategy.signal import Signal

from agents.analyst import invoke_structured


def explain_signal(
    *,
    market_context: MarketContext,
    signal: Signal,
    risk_decision: RiskDecision,
) -> SignalExplanation:
    market_lines = "\n".join(market_context.to_prompt_lines())

    prompt = f"""
You are a trading analyst reviewing a decision already made by a deterministic
system. You are NOT deciding anything — the trade has already been sized,
approved or rejected, and its stop/target already fixed. Your only job is to
explain, in plain language, why this decision makes sense (or doesn't) given
the data below.

OBSERVED MARKET DATA:

{market_lines}

SIGNAL (already generated by the deterministic strategy engine):

{signal.model_dump_json(indent=2)}

RISK DECISION (already made by the deterministic risk engine):

{risk_decision.model_dump_json(indent=2)}

Explain:
- What evidence in the market data SUPPORTS this signal/decision.
- What evidence CONTRADICTS or weakens it.
- A short narrative summary a trader could read in five seconds.

You cannot change the entry, stop, target, quantity, or approval status —
only comment on them.
"""

    return invoke_structured(
        role="signal_explainer",
        label="Signal Explainer",
        prompt=prompt,
        schema=SignalExplanation,
    )
